name: method-name-prediction
dependencies: 
 - python=3.6.8
 - numpy
 - tensorflow
 - docopt
 - urllib3
 - jupyter
 - pydot
 - graphviz
 - sklearn
 - pip:
   - dpu-utils
   - more_itertools
   - watermark
   - jupyter_tensorboard
