name: method-name-prediction
dependencies: 
 - python=3.6.8
 - numpy
 - tensorflow-gpu
 - docopt
 - urllib3
 - jupyter
 - pydot
 - graphviz
 - pip:
   - dpu-utils
   - sklearn
   - more_itertools
   - watermark
   - jupyter_tensorboard
